### ISSUE TITLE
Cannot get default config dir in Tomcat 8.0.x

### ISSUE THREAD

**Issue by victorzinho** [geoladris/core#45]
Noticed on Tomcat 8.0.14 (Debian):

```
SEVERE: Exception sending context initialized event to listener instance of class org.geoladris.servlet.AppContextListener
java.lang.NullPointerException
        at java.io.File.<init>(File.java:277)
        at org.geoladris.servlet.AppContextListener.getConfigDir(AppContextListener.java:105)
        at org.geoladris.servlet.AppContextListener.contextInitialized(AppContextListener.java:43)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4832)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5256)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:581)
        at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1685)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by victorzinho** [comment]
Fixed in 49acb895feff1c9fe9ec5d29142e5ac18d26a93c.
